services:
  - type: web
    name: smarthire-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    rootDir: server
    envVars:
      - key: NODE_ENV
        value: production

  - type: web
    name: smarthire-frontend
    env: static
    region: global
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    rootDir: client
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
